#!/usr/bin/env ruby

require 'mdpdf'

def errmsg
  err_msg = <<-EOS
  1st argment is MarkDown file name or options \n
  2nd argment is outs PDF fine name \n
  OPTION: \n 
  -v => version \n
  -h => help\n
  EOS

  STDERR.print  err_msg
end

if ARGV.length == 2
  mdfile_name = ARGV[0]
  outpdf_name = ARGV[1]
  Mdpdf::Md2Pdf.new(mdfile_name,outpdf_name)
elsif ARGV.length == 1
  argv = ARGV[0]
  case argv
  when '-v'
    puts "mdpdf version is #{Mdpdf::VERSION} "
  when '-h'
    errmsg
  else
    errmsg
  end
else
  errmsg
end

